<a href="https://colab.research.google.com/github/MwamiEric/Blossom-Project-/blob/main/Decision_Tree_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Setup**

In [39]:
# To write a Python 2/3 compatible codebase, the first step is to add this line to the top of each module
from __future__ import division, print_function, unicode_literals

import numpy as np # Importing NumPy, a powerful library for numerical operations, especially with arrays.
import pandas as pd # Importing Pandas, essential for data manipulation and analysis, primarily with DataFrames.

# Setting a random seed (like a starting point for randomness) to ensure that any random operations
# (like splitting data or initializing weights) will produce the same results every time we run the code.
np.random.seed(42)

import matplotlib                    # Importing the entire Matplotlib library, the foundation for creating static, animated, and interactive visualizations in Python.
import matplotlib.pyplot as plt      # Importing the 'pyplot' module from Matplotlib and aliasing it as 'plt'. This module provides a MATLAB-like interface for plotting, making it easy to create various types of plots with just a few lines of code.

# Loading dataset from the specified CSV file into a Pandas DataFrame named 'dataset'.
dataset = pd.read_csv("/HW1_Data.csv")

In [40]:
# Displaying the first few rows of your DataFrame.
dataset.head()

,revenue,outcalls,incalls,months,eqpdays,webcap,marryyes,travel,pcown,creditcd,retcalls,churndep
0,83.53,20.00,1.0,31,745,1,0,0,0,0,4,1
1,29.99,0.00,0.0,52,1441,0,0,0,1,1,3,1
2,37.75,2.67,0.0,25,572,0,0,0,1,1,3,1
3,5.25,0.00,0.0,45,1354,0,0,0,0,0,2,1
4,42.71,8.67,0.0,27,224,1,0,0,0,0,3,1

In [41]:
# Checking for any missing values (NaN) in each column of your DataFrame.
# '.isna()' creates a boolean DataFrame where 'True' indicates a missing value.
# '.sum()' then counts the number of 'True' values (missing values) for each column.
dataset.isna().sum()

revenue     0
outcalls    0
incalls     0
months      0
eqpdays     0
webcap      0
marryyes    0
travel      0
pcown       0
creditcd    0
retcalls    0
churndep    0
dtype: int64

In [42]:
# Customizing global plot settings using Matplotlib's 'rcParams' to control the aesthetics of our visualizations.
# This ensures consistent styling across all your plots.


plt.rcParams['axes.labelsize']= 14      # Setting the font size for the x and y-axis labels to 14 points.
plt.rcParams['xtick.labelsize']= 12     # Setting the font size for the x-axis tick labels (the numbers/text next to the tick marks) to 12 points.
plt.rcParams['ytick.labelsize']= 12     # Setting the font size for the y-axis tick labels to 12 points.
plt.rcParams['xtick.color'] = 'red'     # Setting the color of the x-axis tick marks and their labels to red.
plt.rcParams['ytick.color'] = 'blue'    # Setting the color of the y-axis tick marks and their labels to blue.

# **Training and Visualizing a Decision Tree**

In [ ]:
# Importing the DecisionTreeClassifier from scikit-learn. This is a machine learning algorithm used for classification tasks,
# capable of handling both binary and multi-class classification problems by creating a tree-like model of decisions.
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import plot_tree
import seaborn as sns     # Seaborn documentation can be found here https://seaborn.pydata.org/generated/seaborn.set.html
sns.set(color_codes=True) # Configure Seaborn's default aesthetic parameters in one step.
from scipy import stats   # Import stats package of scipy https://docs.scipy.org/doc/scipy/reference/stats.html#module-scipy.stats
                          # The stats module contains a large number of probability distributions, statistical functions, and statistical tests.

#Split data into features and target
x = dataset.iloc[:,1:11]
y= dataset['churndep']


# Splitting the dataset into training and testing sets with 'x' contains the features (independent variables) and 'y' contains the target (dependent variable).
# test_size=0.2 means 20% of the data will be used for testing, and the remaining 80% for training.

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

#Fit decsion tree model
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train, y_train)


#Plot the decision Tree
plt.figure(figsize=(12,8))
plot_tree(dt_model, feature_names = x.columns, class_names=['1','0'], filled=True)
plt.show()